# Tasks

These are my solutions to the tasks that I must complete for the 2020 Emerging Technology module. My name is Sagheer Ahmad (G00357770@gmit.ie).
***

#### Task: Calculate a square root to 100 decimal places

One of the ways we can calculate the square root of a number is by using Newton's Method.[1,2,3]. Newton's Method uses a specific formula, seen below, to calculate the square root. It is known an an iterative method and approximates roots of equations. The algorithm starts off by guessing the square root of the given number as x > 0. It then computes a more accurate guess by taking the derivative of f(x) to get f'(x) and plug it into the formula. We then repeat the formula until we get a better and more accurate guess. The problem that I encountered with this formula was that it does not print out the value to 100 decimal places. It prints out the first 52 values and the rest are left as Zeros.

<br />

$$ z_{next} = z - \frac{z^2 -x}{2z} $$

<br /> <br />

The formula shown below is another way of calculating the the square root of 2. The first thing the method is doing is setting the x value from the user to, x multiplied by 10 to the power of 200. This will take all the numbers from the right side of the decimal place and brings it to the left side. The method has 2 other variables, one is a variable used in the while loop while the other is a googol. The while loop keeps running until an accurate guess is made. Inside the while loop we are setting b to z and then calculating a better guess for z. The guess is using floor devision because we do not want any decimal places in the answer. The guess is also being bitshifted to the right, the bitshifting shifts the bits of the first operand right by the specified number of bits.[6] Once the guess is accurate the while loop stops and prints out the value. I first had it so the program prints the value z staright away but this was a problem because when it was printed out, the value was a big number with no decimal places. In order to add a decimal place the number had to be converted into a list and the . could be inserted then. The list is then joined together and printed out as a string.

All References can be found in the README of this project.

In [77]:
#Calculate the sqaure root of a number
def sqrt2(x):
    
    """
    A function to calculate the square root of a number x.
    """
    
    # Initial guess for the square root z.
    #z = x / 2
    
    #while abs(x - (z * z)) > 0.000001: Newtons Method
    #Newthon's Method
        #z -= (z*z - x) / (2 * z)
    
    #bring all the numbers from the right to the left
    x = x * (10**(200))
    y = 0
    #set z to a googol
    z = 1 * (10**100)
    
    # Loop until we are happy with the accuracy.
    while y != z:     
        #set y to z
        y = z
        # get the square root and get the floor division
        #bit shift 1 to the right
        z = (y + (x // y)) >> 1
        
    #convert square root to a list
    listZ = list(str(z))
    #add the . after the first number
    listZ.insert(1, '.')
    #join the . to the numbers
    num = "".join(listZ)
    #return the (approximate) square root of x as a string
    return num

##### Tests of the sqrt function - Testing the function with known values

***

In [78]:
#Test the function with random values
sqrt(2)

'1.4142135623730950488016887242096980785696718753769480731766797379907324784621070388503875343276415727'

In [79]:
sqrt(5)

'2.2360679774997896964091736687312762354406183596115257242708972454105209256378048994144144083787822749'

#### Task: Use scipy.stats to verify this value and calculate the associated p value
-------------------------------------------------------------------------------

The Chi-squared test for independence is a statistical hypothesis test like a t-test. It is used to analyse whether two categorical variables are independent. The Wikipedia article in the research section, gives the table below as an example [1],
stating the Chi-squared value based on it is approximately 24.6. <br><br>

|             | A   | B   | C   | D   | Total  |
| ----------- | ----| ----| ----| ----|--------|
| White collar| 90  | 60  | 104 | 95  | 349    |
| Blue collar | 30  | 50  | 51  | 20  | 151    |
| No collar   | 30  | 40  | 45  | 35  | 150    |
| Total       | 150 | 150 | 200 | 150 | 650    |

<br><br>

The code below is verifying that the chi square value is correct and also prints out the p value. The code first creates a table with the data given and prints it out using the panda library.[2] The table that is printed is the same table as seen above. The data is stored in a variable named "data". We next use the scipy.stats library to figure out the Expected value, the p value, the actual chi square value and the degree of freedom. We use the  " stats.chi2_contingency(data)" to get these values. This method returns all those values based on the marginal sums under the assumption of independence. The assumptions are:
1. the observations are independent and
2. normally distributed 

All the references used in this task can be found in the README.

In [7]:
#required class - print out the table
import scipy.stats as stats

#data to be inserted into the columns
data = [[90,60,104,95], [30,50,51,20],[30,40,45,35]]

#returns 4 values
#Get the chi square value, the p value, the degree of freedom and the expected frequencies
chi2, p, dof, ex = stats.chi2_contingency(data)

#the chi squared value
print("The approximate chi squared value is: %.1f" % chi2, "\n")
#the associated p value
print("The associated p value is:", p, "\n")
# the degrees of freedom - number of values in the final calculation of a statistic that are free to vary
print("The Degree of Freedom is:" ,dof, "\n")
#the expected frequencies
print("The expected frequencies are: \n",ex, "\n")

The approximate chi squared value is: 24.6 

The associated p value is: 0.0004098425861096696 

The Degree of Freedom is: 6 

The expected frequencies are: 
 [[ 80.53846154  80.53846154 107.38461538  80.53846154]
 [ 34.84615385  34.84615385  46.46153846  34.84615385]
 [ 34.61538462  34.61538462  46.15384615  34.61538462]] 

